<?php
// Education Master Data — auto-generated for Candidate Onboarding

return [

    'qualifications' => [
        'Doctorate' => [
            'courses' => [
                'Ph.D.',
                'D.Sc.',
                'D.Litt.',
                'D.Phil.',
                'D.Tech.',
                'M.D. (Doctor of Medicine)',
                'D.D.S.',
            ],
            'course_types' => [
                'Full Time',
                'Part Time',
            ],
        ],
        'Post Graduate' => [
            'courses' => [
                'M.Tech / M.E.',
                'MCA',
                'MBA',
                'M.Com',
                'M.Sc',
                'M.A.',
                'M.S.',
                'M.Ed',
                'M.Pharm',
                'M.Des',
                'LLM',
                'MSW',
                'MHM',
                'MPH',
                'M.Arch',
                'M.Plan',
                'M.P.Ed',
                'M.D. / MS (Medical)',
                'MDS (Dental)',
                'PGDM',
                'PG Diploma',
                'Others',
            ],
            'course_types' => [
                'Full Time',
                'Part Time',
                'Distance Learning',
                'Correspondence',
            ],
        ],
        'Graduate' => [
            'courses' => [
                'B.Tech / B.E.',
                'B.Sc',
                'B.Com',
                'B.A.',
                'BBA / BMS',
                'BCA',
                'LLB',
                'B.Ed',
                'MBBS',
                'BDS',
                'B.Pharm',
                'B.Arch',
                'B.Des',
                'BHM',
                'B.P.Ed',
                'B.Sc Nursing',
                'BSW',
                'B.Sc Agriculture',
                'B.Voc',
                'Others',
            ],
            'course_types' => [
                'Full Time',
                'Part Time',
                'Distance Learning',
                'Correspondence',
            ],
        ],
        'Diploma' => [
            'courses' => [
                'Polytechnic Diploma (Engineering)',
                'Diploma in Computer Application (DCA)',
                'Diploma in Business Administration',
                'Diploma in Pharmacy',
                'Diploma in Hotel Management',
                'Diploma in Education (D.Ed)',
                'Diploma in Nursing',
                'Diploma in Fashion Design',
                'ITI Certificate',
                'Post Graduate Diploma',
                'Others',
            ],
            'course_types' => [
                'Full Time',
                'Part Time',
                'Distance Learning',
            ],
        ],
        'Class XII' => [
            'courses' => [
                'Science Stream',
                'Commerce Stream',
                'Arts / Humanities',
                'Vocational',
                'Other',
            ],
            'course_types' => [
                'Regular',
                'Distance / NIOS',
            ],
        ],
        'Class X' => [
            'courses' => [
                'Secondary Education (Class X)',
            ],
            'course_types' => [
                'Regular',
                'Distance / NIOS',
            ],
        ],
        'Below Class X' => [
            'courses' => [
                'Primary Education',
                'Upper Primary',
                'Other',
            ],
            'course_types' => [
                'Regular',
            ],
        ],
    ],

    'specializations' => [
        'B.Tech / B.E.' => [
            'Computer Science & Engineering',
            'Information Technology',
            'Electronics & Communication Engineering',
            'Electrical Engineering',
            'Mechanical Engineering',
            'Civil Engineering',
            'Chemical Engineering',
            'Automobile Engineering',
            'Aerospace Engineering',
            'Biomedical Engineering',
            'Data Science',
            'Artificial Intelligence & Machine Learning',
            'Robotics & Automation',
            'Environmental Engineering',
            'Mining Engineering',
            'Textile Engineering',
            'Instrumentation Engineering',
            'Production Engineering',
            'Industrial Engineering',
            'Others',
        ],
        'M.Tech / M.E.' => [
            'Computer Science & Engineering',
            'Information Technology',
            'Electronics & Communication',
            'VLSI Design',
            'Power Systems',
            'Structural Engineering',
            'Thermal Engineering',
            'Machine Design',
            'Embedded Systems',
            'Signal Processing',
            'Artificial Intelligence',
            'Data Science',
            'Cybersecurity',
            'Wireless Communication',
            'Environmental Engineering',
            'Manufacturing Engineering',
            'Others',
        ],
        'MBA' => [
            'Marketing',
            'Finance',
            'Human Resources',
            'Operations Management',
            'Business Analytics',
            'International Business',
            'IT Management',
            'Healthcare Management',
            'Supply Chain Management',
            'Entrepreneurship',
            'Retail Management',
            'Rural Management',
            'Tourism & Hospitality Management',
            'Others',
        ],
        'PGDM' => [
            'Marketing',
            'Finance',
            'Human Resources',
            'Operations Management',
            'Business Analytics',
            'International Business',
            'IT Management',
            'Others',
        ],
        'MCA' => [
            'Software Development',
            'Web Technologies',
            'Data Science',
            'Cloud Computing',
            'Cybersecurity',
            'Database Management',
            'Networking',
            'General / Others',
        ],
        'BCA' => [
            'Computer Applications',
            'Web Development',
            'Software Development',
            'Database Management',
            'Networking',
            'General / Others',
        ],
        'M.Com' => [
            'Accounting & Finance',
            'Banking & Insurance',
            'Business Policy & Administration',
            'Financial Management',
            'Taxation',
            'Others',
        ],
        'B.Com' => [
            'Accounting & Finance',
            'Banking & Insurance',
            'Computer Applications',
            'Taxation',
            'Business Studies',
            'Co-operation',
            'General',
            'Others',
        ],
        'B.A.' => [
            'English Literature',
            'Hindi Literature',
            'History',
            'Political Science',
            'Sociology',
            'Geography',
            'Psychology',
            'Philosophy',
            'Economics',
            'Public Administration',
            'Social Work',
            'Others',
        ],
        'M.A.' => [
            'English Literature',
            'Hindi Literature',
            'History',
            'Political Science',
            'Sociology',
            'Geography',
            'Psychology',
            'Economics',
            'Philosophy',
            'Public Administration',
            'Journalism & Mass Communication',
            'Others',
        ],
        'B.Sc' => [
            'Physics',
            'Chemistry',
            'Mathematics',
            'Biology',
            'Computer Science',
            'Statistics',
            'Microbiology',
            'Biotechnology',
            'Electronics',
            'Environmental Science',
            'Agriculture',
            'Home Science',
            'Others',
        ],
        'M.Sc' => [
            'Physics',
            'Chemistry',
            'Mathematics',
            'Computer Science',
            'Biotechnology',
            'Microbiology',
            'Environmental Science',
            'Statistics',
            'Electronics',
            'Zoology',
            'Botany',
            'Bioinformatics',
            'Others',
        ],
        'BBA / BMS' => [
            'Marketing',
            'Finance',
            'Human Resources',
            'International Business',
            'Entrepreneurship',
            'General Management',
            'Others',
        ],
        'LLB' => [
            'Corporate Law',
            'Criminal Law',
            'Constitutional Law',
            'Intellectual Property Law',
            'Cyber Law',
            'Labour Law',
            'Family Law',
            'General / Others',
        ],
        'LLM' => [
            'Corporate Law',
            'International Law',
            'Criminal Law',
            'Intellectual Property Law',
            'Constitutional Law',
            'Labour Law',
            'Cyber Law',
            'Others',
        ],
        'B.Ed' => [
            'Primary Education',
            'Secondary Education',
            'Special Education',
            'Physical Education',
            'Mathematics',
            'Science',
            'Social Science',
            'Language',
            'Others',
        ],
        'M.Ed' => [
            'Educational Administration',
            'Educational Technology',
            'Curriculum Design',
            'Special Education',
            'Guidance & Counseling',
            'Others',
        ],
        'MBBS' => [
            'General Medicine',
        ],
        'M.D. / MS (Medical)' => [
            'General Medicine',
            'General Surgery',
            'Paediatrics',
            'Orthopaedics',
            'Gynaecology & Obstetrics',
            'Dermatology',
            'Radiology',
            'Anaesthesiology',
            'Psychiatry',
            'Ophthalmology',
            'ENT',
            'Others',
        ],
        'BDS' => [
            'Dental Surgery',
        ],
        'MDS (Dental)' => [
            'Orthodontics',
            'Oral Surgery',
            'Periodontics',
            'Pedodontics',
            'Prosthodontics',
            'Oral Pathology',
            'Others',
        ],
        'B.Pharm' => [
            'Pharmaceutics',
            'Pharmacology',
            'Pharmaceutical Chemistry',
            'Quality Assurance',
            'Others',
        ],
        'M.Pharm' => [
            'Pharmaceutics',
            'Pharmacology',
            'Pharmaceutical Chemistry',
            'Quality Assurance',
            'Drug Regulatory Affairs',
            'Others',
        ],
        'B.Arch' => [
            'Urban Design',
            'Interior Architecture',
            'Landscape Architecture',
            'Others',
        ],
        'M.Arch' => [
            'Urban Planning',
            'Interior Design',
            'Landscape Architecture',
            'Urban Design',
            'Others',
        ],
        'B.Des' => [
            'Graphic Design',
            'Fashion Design',
            'Industrial Design',
            'UX/UI Design',
            'Interior Design',
            'Others',
        ],
        'M.Des' => [
            'Graphic Design',
            'Fashion Design',
            'Industrial Design',
            'UX/UI Design',
            'Interior Design',
            'Others',
        ],
        'B.Sc Nursing' => [
            'Medical-Surgical Nursing',
            'Community Nursing',
            'Paediatric Nursing',
            'Obstetric Nursing',
            'General / Others',
        ],
        'MSW' => [
            'Social Work',
            'Community Development',
            'HR & Labour Welfare',
            'Medical Social Work',
            'Rural Development',
            'Others',
        ],
        'BHM' => [
            'Food & Beverage',
            'Front Office',
            'Housekeeping',
            'Culinary Arts',
            'General / Others',
        ],
        'MHM' => [
            'Food & Beverage Management',
            'Hotel Operations',
            'Event Management',
            'Tourism Management',
            'Others',
        ],
        'B.Sc Agriculture' => [
            'Agronomy',
            'Horticulture',
            'Plant Pathology',
            'Soil Science',
            'Agricultural Economics',
            'Others',
        ],
        'Polytechnic Diploma (Engineering)' => [
            'Civil Engineering',
            'Mechanical Engineering',
            'Electrical Engineering',
            'Electronics Engineering',
            'Computer Technology',
            'Information Technology',
            'Automobile Engineering',
            'Chemical Engineering',
            'Textile Technology',
            'Others',
        ],
        'Diploma in Computer Application (DCA)' => [
            'Computer Applications',
            'Office Automation',
            'Tally & Accounting Software',
            'Others',
        ],
        'Diploma in Business Administration' => [
            'Business Administration',
            'Marketing',
            'Finance',
            'Others',
        ],
        'Diploma in Pharmacy' => [
            'Pharmacy',
            'Clinical Pharmacy',
            'Others',
        ],
        'Diploma in Hotel Management' => [
            'Food & Beverage',
            'Front Office',
            'Housekeeping',
            'Culinary Arts',
            'Others',
        ],
        'Diploma in Education (D.Ed)' => [
            'Primary Education',
            'Special Education',
            'Others',
        ],
        'ITI Certificate' => [
            'Electrician',
            'Fitter',
            'Turner',
            'Welder',
            'Plumber',
            'Mechanic (Motor Vehicle)',
            'Electronic Mechanic',
            'Computer Operator & Programming Assistant (COPA)',
            'Draughtsman (Civil)',
            'Draughtsman (Mechanical)',
            'Instrument Mechanic',
            'Sheet Metal Worker',
            'Others',
        ],
        'Science Stream' => [
            'PCM (Physics, Chemistry, Maths)',
            'PCB (Physics, Chemistry, Biology)',
            'PCMB (Physics, Chemistry, Maths, Biology)',
            'PCM with Computer Science',
            'Other',
        ],
        'Commerce Stream' => [
            'With Mathematics',
            'Without Mathematics',
            'With Computer Application',
            'Other',
        ],
        'Arts / Humanities' => [
            'History & Political Science',
            'Psychology',
            'Sociology',
            'Geography',
            'Economics',
            'Literature',
            'Other',
        ],
        'Vocational' => [
            'Computer Application',
            'Automobile Technology',
            'Healthcare',
            'Agriculture',
            'Fashion Studies',
            'Other',
        ],
        'Ph.D.' => [
            'Computer Science',
            'Electronics',
            'Physics',
            'Chemistry',
            'Mathematics',
            'Management',
            'Commerce',
            'Economics',
            'English',
            'History',
            'Sociology',
            'Life Sciences',
            'Environmental Science',
            'Education',
            'Law',
            'Agriculture',
            'Others',
        ],
        'D.Sc.' => [
            'Physical Sciences',
            'Life Sciences',
            'Engineering',
            'Others',
        ],
        'D.Litt.' => [
            'Languages',
            'History',
            'Philosophy',
            'Social Sciences',
            'Others',
        ],
        'Secondary Education (Class X)' => [
            'General',
        ],
        'Primary Education' => [
            'General',
        ],
        'Upper Primary' => [
            'General',
        ],
        'Others' => [
            'General / Not Listed',
        ],
    ],

    'skill_suggestions' => [
        'B.Tech / B.E.|||Computer Science & Engineering' => [
            'Java',
            'Python',
            'C++',
            'JavaScript',
            'HTML',
            'CSS',
            'SQL / MySQL',
            'React.js',
            'Node.js',
            'PHP',
            'Git',
            'Data Structures & Algorithms',
            'Operating Systems',
            'Computer Networks',
            'MongoDB',
            'REST APIs',
        ],
        'B.Tech / B.E.|||Information Technology' => [
            'Java',
            'Python',
            'JavaScript',
            'HTML',
            'CSS',
            'SQL / MySQL',
            'React.js',
            'Node.js',
            'PHP',
            'Git',
            'Networking',
            'Cybersecurity Basics',
            'Linux',
            'Cloud Computing Basics',
            'REST APIs',
        ],
        'B.Tech / B.E.|||Electronics & Communication Engineering' => [
            'Embedded C',
            'Circuit Design',
            'PCB Design',
            'MATLAB',
            'VLSI',
            'Arduino',
            'Raspberry Pi',
            'Signal Processing',
            'Microcontrollers',
            'Communication Systems',
            'AutoCAD',
        ],
        'B.Tech / B.E.|||Electrical Engineering' => [
            'Electrical Wiring',
            'PLC / SCADA',
            'AutoCAD Electrical',
            'Power Systems',
            'Motor Control',
            'Panel Design',
            'Switchgear',
            'Transformers',
            'ETAP',
            'MATLAB',
        ],
        'B.Tech / B.E.|||Mechanical Engineering' => [
            'AutoCAD',
            'SolidWorks',
            'CATIA',
            'ANSYS',
            'Manufacturing Processes',
            'GD&T',
            'CNC Programming',
            'Welding',
            'Quality Control',
            'Thermodynamics',
            'MS Office',
        ],
        'B.Tech / B.E.|||Civil Engineering' => [
            'AutoCAD',
            'Staad.Pro',
            'REVIT',
            'Surveying',
            'Construction Management',
            'Quantity Estimation',
            'MS Project',
            'Primavera',
            'Concrete Technology',
            'GIS',
        ],
        'B.Tech / B.E.|||Automobile Engineering' => [
            'AutoCAD',
            'CATIA',
            'Vehicle Dynamics',
            'Engine Systems',
            'Automotive Electronics',
            'EV Technology',
            'MATLAB',
        ],
        'B.Tech / B.E.|||Data Science' => [
            'Python',
            'R',
            'Machine Learning',
            'Deep Learning',
            'SQL',
            'Pandas',
            'NumPy',
            'TensorFlow',
            'PowerBI',
            'Tableau',
            'Statistics',
            'Data Visualization',
        ],
        'B.Tech / B.E.|||Artificial Intelligence & Machine Learning' => [
            'Python',
            'Machine Learning',
            'Deep Learning',
            'TensorFlow',
            'PyTorch',
            'NLP',
            'Computer Vision',
            'SQL',
            'Statistics',
            'Pandas',
            'Scikit-learn',
        ],
        'M.Tech / M.E.|||Computer Science & Engineering' => [
            'Advanced Algorithms',
            'Machine Learning',
            'Deep Learning',
            'Python',
            'Java',
            'Cloud Computing',
            'Big Data',
            'Research Writing',
            'Data Analysis',
            'Cybersecurity',
            'Distributed Systems',
        ],
        'M.Tech / M.E.|||Data Science' => [
            'Python',
            'R',
            'Machine Learning',
            'Deep Learning',
            'Big Data (Hadoop/Spark)',
            'SQL',
            'TensorFlow',
            'Statistics',
            'Data Visualization',
            'NLP',
        ],
        'MBA|||Marketing' => [
            'Digital Marketing',
            'SEO / SEM',
            'Social Media Marketing',
            'Market Research',
            'CRM',
            'Sales',
            'Communication',
            'Brand Management',
            'Content Marketing',
            'Google Analytics',
        ],
        'MBA|||Finance' => [
            'Financial Analysis',
            'Excel / Advanced Excel',
            'Financial Modeling',
            'Tally',
            'Accounting',
            'Taxation',
            'SAP FICO',
            'Valuation',
            'Investment Analysis',
            'Banking Operations',
        ],
        'MBA|||Human Resources' => [
            'Recruitment',
            'Payroll Processing',
            'HR Policies',
            'HRMS Software',
            'Performance Management',
            'Labour Law',
            'Talent Acquisition',
            'Employee Relations',
            'Training & Development',
            'MS Office',
        ],
        'MBA|||Operations Management' => [
            'Supply Chain Management',
            'Logistics',
            'ERP (SAP MM)',
            'Inventory Management',
            'Production Planning',
            'Lean Manufacturing',
            'Six Sigma',
            'Warehouse Management',
            'Procurement',
        ],
        'MBA|||Business Analytics' => [
            'Python',
            'R',
            'SQL',
            'PowerBI',
            'Tableau',
            'Excel',
            'Statistics',
            'Machine Learning Basics',
            'Data Visualization',
            'Business Intelligence',
        ],
        'PGDM|||Marketing' => [
            'Digital Marketing',
            'SEO / SEM',
            'Social Media Marketing',
            'Market Research',
            'CRM',
            'Sales',
            'Communication',
            'Brand Management',
        ],
        'PGDM|||Finance' => [
            'Financial Analysis',
            'Excel / Advanced Excel',
            'Financial Modeling',
            'Tally',
            'Accounting',
            'Taxation',
            'SAP FICO',
        ],
        'MCA|||Software Development' => [
            'Java',
            '.NET / C#',
            'PHP',
            'Python',
            'Web Development',
            'Database (MySQL, Oracle)',
            'React.js',
            'Angular',
            'Git',
        ],
        'MCA|||Web Technologies' => [
            'HTML',
            'CSS',
            'JavaScript',
            'PHP',
            'React.js',
            'Node.js',
            'MySQL',
            'WordPress',
            'REST APIs',
            'Git',
        ],
        'MCA|||Data Science' => [
            'Python',
            'R',
            'SQL',
            'Machine Learning',
            'Data Analysis',
            'Pandas',
            'NumPy',
            'Tableau',
            'PowerBI',
        ],
        'BCA|||Computer Applications' => [
            'Java',
            'C++',
            'HTML',
            'CSS',
            'JavaScript',
            'PHP',
            'MySQL',
            'MS Office',
            'Python',
            'Git',
        ],
        'B.Com|||Accounting & Finance' => [
            'Tally ERP 9 / Tally Prime',
            'GST Filing',
            'MS Excel',
            'Accounting',
            'Bookkeeping',
            'Income Tax',
            'Financial Reporting',
            'Audit',
        ],
        'B.Com|||Banking & Insurance' => [
            'Banking Operations',
            'Insurance Concepts',
            'MS Excel',
            'Tally',
            'Financial Products',
            'Customer Service',
        ],
        'B.Com|||Taxation' => [
            'GST',
            'Income Tax',
            'TDS',
            'Tally',
            'MS Excel',
            'Tax Filing',
            'Audit',
            'Accounting',
        ],
        'B.Com|||General' => [
            'Tally ERP',
            'MS Excel',
            'Accounting',
            'GST',
            'Bookkeeping',
            'Communication',
            'MS Office',
        ],
        'M.Com|||Accounting & Finance' => [
            'Advanced Accounting',
            'Financial Analysis',
            'Tally',
            'SAP FICO',
            'Taxation',
            'Financial Reporting',
            'Audit',
            'MS Excel',
        ],
        'B.Sc|||Computer Science' => [
            'C',
            'C++',
            'Java',
            'Python',
            'HTML',
            'CSS',
            'MySQL',
            'Linux / Unix',
            'Data Structures',
            'Web Development Basics',
        ],
        'B.Sc|||Mathematics' => [
            'Mathematics',
            'Statistics',
            'Python',
            'R',
            'MATLAB',
            'Data Analysis',
            'MS Excel',
        ],
        'B.Sc|||Biotechnology' => [
            'Lab Techniques',
            'PCR',
            'ELISA',
            'Cell Culture',
            'Bioinformatics Basics',
            'Research Writing',
            'Microsoft Office',
        ],
        'M.Sc|||Computer Science' => [
            'Python',
            'Java',
            'Machine Learning',
            'Data Analysis',
            'SQL',
            'Linux',
            'Research Methods',
            'Cloud Computing',
        ],
        'BBA / BMS|||Marketing' => [
            'Digital Marketing',
            'Social Media Marketing',
            'CRM',
            'Communication',
            'Market Research',
            'MS Office',
            'Sales',
        ],
        'BBA / BMS|||Finance' => [
            'MS Excel',
            'Tally',
            'Accounting',
            'Financial Analysis',
            'Banking Basics',
            'Communication',
        ],
        'BBA / BMS|||Human Resources' => [
            'Recruitment Basics',
            'HR Concepts',
            'MS Office',
            'Communication',
            'Payroll Basics',
        ],
        'LLB|||Corporate Law' => [
            'Legal Research',
            'Contract Drafting',
            'Corporate Compliance',
            'SEBI Regulations',
            'Company Law',
            'Legal Writing',
        ],
        'LLB|||Criminal Law' => [
            'Legal Research',
            'Court Procedure',
            'Criminal Procedure Code',
            'Evidence Law',
            'Legal Writing',
            'Litigation',
        ],
        'LLB|||General / Others' => [
            'Legal Research',
            'Legal Writing',
            'Contract Drafting',
            'Court Procedure',
            'MS Word',
            'Communication',
        ],
        'LLM|||Corporate Law' => [
            'Advanced Corporate Law',
            'Mergers & Acquisitions',
            'Contract Drafting',
            'SEBI/RBI Regulations',
            'Legal Research',
            'Compliance Management',
        ],
        'B.Ed|||Secondary Education' => [
            'Lesson Planning',
            'Classroom Management',
            'Educational Technology',
            'Child Psychology',
            'Curriculum Development',
            'Communication',
            'MS Office',
        ],
        'B.Ed|||Primary Education' => [
            'Lesson Planning',
            'Classroom Management',
            'Child Development',
            'Activity-Based Learning',
            'Communication',
            'MS Office',
        ],
        'Polytechnic Diploma (Engineering)|||Civil Engineering' => [
            'AutoCAD',
            'Surveying',
            'Concrete Technology',
            'Quantity Estimation',
            'Construction Supervision',
            'MS Office',
        ],
        'Polytechnic Diploma (Engineering)|||Mechanical Engineering' => [
            'AutoCAD',
            'SolidWorks',
            'Workshop Skills',
            'CNC Basics',
            'Quality Control',
            'Blueprint Reading',
        ],
        'Polytechnic Diploma (Engineering)|||Electrical Engineering' => [
            'Electrical Wiring',
            'Panel Wiring',
            'PLC Basics',
            'Electrical Diagrams',
            'Switchgear',
            'Maintenance',
        ],
        'Polytechnic Diploma (Engineering)|||Computer Technology' => [
            'C',
            'Java',
            'HTML',
            'CSS',
            'MySQL',
            'MS Office',
            'Networking Basics',
            'Python Basics',
        ],
        'Polytechnic Diploma (Engineering)|||Electronics Engineering' => [
            'Circuit Design',
            'PCB Design',
            'Arduino',
            'Embedded C',
            'Soldering',
            'Electronic Testing',
        ],
        'Diploma in Computer Application (DCA)|||Computer Applications' => [
            'MS Office',
            'Tally',
            'Internet Basics',
            'HTML Basics',
            'Typing',
            'Data Entry',
            'Email Communication',
        ],
        'ITI Certificate|||Electrician' => [
            'Electrical Wiring',
            'Panel Installation',
            'Safety Procedures',
            'Electrical Tools',
            'Motor Winding',
            'Troubleshooting',
        ],
        'ITI Certificate|||Fitter' => [
            'Fitting & Assembly',
            'Blueprint Reading',
            'Lathe Operation',
            'Measuring Instruments',
            'Safety Procedures',
            'Quality Inspection',
        ],
        'ITI Certificate|||Welder' => [
            'Arc Welding',
            'MIG Welding',
            'TIG Welding',
            'Welding Safety',
            'Blueprint Reading',
            'Metal Cutting',
        ],
        'ITI Certificate|||Mechanic (Motor Vehicle)' => [
            'Engine Overhaul',
            'Brake System',
            'Electrical Systems',
            'Vehicle Diagnostics',
            'Fuel Systems',
            'Safety Procedures',
        ],
        'ITI Certificate|||Computer Operator & Programming Assistant (COPA)' => [
            'MS Office',
            'Tally',
            'Data Entry',
            'Internet Usage',
            'Basic Programming',
            'Typing',
            'Printer / Hardware Basics',
        ],
        'Science Stream|||PCM (Physics, Chemistry, Maths)' => [
            'Mathematics',
            'Physics',
            'Chemistry',
            'MS Excel',
            'Computer Basics',
            'Communication',
        ],
        'Science Stream|||PCB (Physics, Chemistry, Biology)' => [
            'Biology',
            'Chemistry',
            'Lab Work',
            'Research Basics',
            'Communication',
            'MS Office',
        ],
        'Commerce Stream|||With Mathematics' => [
            'Accountancy',
            'Economics',
            'MS Excel',
            'Tally Basics',
            'Communication',
            'Business Studies',
        ],
        'Commerce Stream|||Without Mathematics' => [
            'Accountancy',
            'Business Studies',
            'Communication',
            'MS Office',
            'Customer Service',
        ],
    ],

    'role_suggestions' => [
        'B.Tech / B.E.|||Computer Science & Engineering' => [
            'Software Developer',
            'Frontend Developer',
            'Backend Developer',
            'Full Stack Developer',
            'Web Developer',
            'Mobile App Developer',
            'Data Analyst',
            'QA Engineer / Software Tester',
            'IT Support Engineer',
            'System Administrator',
            'DevOps Engineer',
            'Junior Software Engineer',
        ],
        'B.Tech / B.E.|||Information Technology' => [
            'IT Support Engineer',
            'Software Developer',
            'Web Developer',
            'Network Engineer',
            'System Administrator',
            'Cloud Support Engineer',
            'Database Administrator',
            'QA Engineer',
            'Frontend Developer',
            'Backend Developer',
        ],
        'B.Tech / B.E.|||Electronics & Communication Engineering' => [
            'Electronics Engineer',
            'Embedded Systems Engineer',
            'VLSI Design Engineer',
            'Hardware Engineer',
            'Test Engineer',
            'PCB Designer',
            'Communication Engineer',
            'Automation Engineer',
            'Service Engineer',
            'Technical Support Engineer',
        ],
        'B.Tech / B.E.|||Electrical Engineering' => [
            'Electrical Engineer',
            'Electrical Supervisor',
            'Panel Design Engineer',
            'Maintenance Engineer',
            'Power System Engineer',
            'Site Engineer',
            'Project Engineer',
            'Switchgear Engineer',
            'Energy Auditor',
        ],
        'B.Tech / B.E.|||Mechanical Engineering' => [
            'Mechanical Engineer',
            'Design Engineer',
            'Production Engineer',
            'Quality Engineer',
            'Maintenance Engineer',
            'CAD Engineer',
            'Project Engineer',
            'Service Engineer',
            'R&D Engineer',
        ],
        'B.Tech / B.E.|||Civil Engineering' => [
            'Civil Engineer',
            'Site Engineer',
            'Structural Engineer',
            'AutoCAD Draughtsman',
            'Project Manager',
            'Quantity Surveyor',
            'Estimation Engineer',
            'Town Planner',
            'Geotechnical Engineer',
        ],
        'B.Tech / B.E.|||Data Science' => [
            'Data Analyst',
            'Data Scientist',
            'Business Analyst',
            'Machine Learning Engineer',
            'BI Developer',
            'Data Engineer',
            'Research Analyst',
        ],
        'B.Tech / B.E.|||Artificial Intelligence & Machine Learning' => [
            'Machine Learning Engineer',
            'AI Engineer',
            'Data Scientist',
            'NLP Engineer',
            'Computer Vision Engineer',
            'Research Engineer',
            'Data Analyst',
        ],
        'M.Tech / M.E.|||Computer Science & Engineering' => [
            'Senior Software Engineer',
            'Research Engineer',
            'Data Scientist',
            'Machine Learning Engineer',
            'AI Researcher',
            'Technical Lead',
            'Cloud Architect',
            'Software Architect',
        ],
        'M.Tech / M.E.|||Data Science' => [
            'Data Scientist',
            'Machine Learning Engineer',
            'AI Researcher',
            'BI Analyst',
            'Data Engineer',
            'Research Scientist',
        ],
        'MBA|||Marketing' => [
            'Marketing Executive',
            'Digital Marketing Executive',
            'Sales Executive',
            'Business Development Executive',
            'Marketing Analyst',
            'Brand Manager',
            'SEO Executive',
            'Product Marketing Manager',
            'Market Research Analyst',
        ],
        'MBA|||Finance' => [
            'Finance Executive',
            'Accounts Executive',
            'Financial Analyst',
            'Banking Executive',
            'Investment Analyst',
            'Tax Consultant',
            'Credit Analyst',
            'Treasury Manager',
        ],
        'MBA|||Human Resources' => [
            'HR Executive',
            'Recruiter',
            'Talent Acquisition Executive',
            'HR Manager',
            'HR Business Partner',
            'Payroll Executive',
            'Training & Development Executive',
            'HR Generalist',
        ],
        'MBA|||Operations Management' => [
            'Operations Executive',
            'Supply Chain Executive',
            'Logistics Coordinator',
            'Production Planning Officer',
            'Operations Manager',
            'Procurement Executive',
            'Warehouse Manager',
        ],
        'MBA|||Business Analytics' => [
            'Business Analyst',
            'Data Analyst',
            'Analytics Consultant',
            'BI Analyst',
            'Product Analyst',
            'Market Research Analyst',
        ],
        'PGDM|||Marketing' => [
            'Marketing Executive',
            'Sales Executive',
            'Business Development Executive',
            'Digital Marketing Executive',
            'Brand Executive',
        ],
        'PGDM|||Finance' => [
            'Finance Executive',
            'Accounts Executive',
            'Financial Analyst',
            'Banking Executive',
            'Tax Consultant',
        ],
        'MCA|||Software Development' => [
            'Software Developer',
            'Java Developer',
            '.NET Developer',
            'Web Developer',
            'PHP Developer',
            'Python Developer',
            'Backend Developer',
            'Database Administrator',
        ],
        'MCA|||Web Technologies' => [
            'Web Developer',
            'Frontend Developer',
            'PHP Developer',
            'WordPress Developer',
            'UI Developer',
            'Full Stack Developer',
        ],
        'BCA|||Computer Applications' => [
            'Junior Developer',
            'Web Designer',
            'IT Support Executive',
            'Data Entry Operator',
            'Junior Programmer',
            'Technical Support',
        ],
        'B.Com|||Accounting & Finance' => [
            'Accountant',
            'Accounts Executive',
            'Finance Executive',
            'Billing Executive',
            'Audit Assistant',
            'Tax Executive',
            'Junior Accountant',
            'Accounts Payable / Receivable Executive',
        ],
        'B.Com|||Banking & Insurance' => [
            'Banking Executive',
            'Insurance Advisor',
            'Customer Service Executive',
            'Loan Officer',
            'Branch Banking Executive',
            'Operations Executive',
        ],
        'B.Com|||Taxation' => [
            'Tax Consultant',
            'GST Executive',
            'Accounts Executive',
            'Tax Assistant',
            'Audit Executive',
        ],
        'B.Com|||General' => [
            'Accountant',
            'Accounts Executive',
            'Finance Executive',
            'Billing Executive',
            'Back Office Executive',
            'Data Entry Operator',
        ],
        'M.Com|||Accounting & Finance' => [
            'Senior Accountant',
            'Finance Manager',
            'Financial Analyst',
            'Audit Executive',
            'Tax Manager',
            'Commerce Lecturer',
        ],
        'BBA / BMS|||Marketing' => [
            'Sales Executive',
            'Marketing Executive',
            'Business Development Executive',
            'Customer Support Executive',
            'Field Sales Executive',
        ],
        'BBA / BMS|||Human Resources' => [
            'HR Executive',
            'Recruiter',
            'HR Trainee',
            'Administrative Assistant',
        ],
        'BBA / BMS|||Finance' => [
            'Finance Executive',
            'Accounts Assistant',
            'Banking Executive',
        ],
        'LLB|||Corporate Law' => [
            'Corporate Lawyer',
            'Legal Executive',
            'Compliance Officer',
            'Legal Associate',
            'Contract Manager',
            'In-House Counsel',
        ],
        'LLB|||Criminal Law' => [
            'Advocate',
            'Public Prosecutor',
            'Legal Associate',
            'Court Clerk',
            'Legal Advisor',
        ],
        'LLB|||General / Others' => [
            'Advocate',
            'Legal Executive',
            'Legal Advisor',
            'Compliance Officer',
            'Paralegal',
        ],
        'LLM|||Corporate Law' => [
            'Senior Advocate',
            'Corporate Lawyer',
            'M&A Specialist',
            'Compliance Manager',
            'Legal Counsel',
        ],
        'B.Ed|||Secondary Education' => [
            'Secondary School Teacher',
            'Subject Teacher',
            'Tutor',
            'Academic Coordinator',
            'Content Developer',
        ],
        'B.Ed|||Primary Education' => [
            'Primary School Teacher',
            'Pre-Primary Teacher',
            'Kindergarten Teacher',
            'Tutor',
            'Special Educator',
        ],
        'M.Ed|||Educational Administration' => [
            'Principal',
            'Vice Principal',
            'Education Administrator',
            'Curriculum Designer',
            'Academic Director',
        ],
        'B.Sc|||Computer Science' => [
            'Junior Developer',
            'IT Support Executive',
            'Data Entry Operator',
            'Lab Technician',
            'Technical Assistant',
        ],
        'B.Sc|||Biotechnology' => [
            'Lab Technician',
            'Research Assistant',
            'Quality Control Executive',
            'Clinical Research Associate',
            'Biotech Trainee',
        ],
        'M.Sc|||Computer Science' => [
            'Software Developer',
            'Data Analyst',
            'Research Engineer',
            'Technical Associate',
            'IT Executive',
        ],
        'Polytechnic Diploma (Engineering)|||Civil Engineering' => [
            'Junior Civil Engineer',
            'Site Supervisor',
            'AutoCAD Draughtsman',
            'Field Engineer',
            'Estimation Assistant',
        ],
        'Polytechnic Diploma (Engineering)|||Mechanical Engineering' => [
            'Junior Mechanical Engineer',
            'Production Supervisor',
            'Maintenance Technician',
            'Quality Inspector',
            'CAD Draughtsman',
        ],
        'Polytechnic Diploma (Engineering)|||Electrical Engineering' => [
            'Electrical Technician',
            'Junior Electrical Engineer',
            'Maintenance Electrician',
            'Panel Wiring Technician',
        ],
        'Polytechnic Diploma (Engineering)|||Computer Technology' => [
            'Junior Developer',
            'IT Support Technician',
            'Data Entry Operator',
            'Computer Operator',
            'Technical Assistant',
        ],
        'Diploma in Computer Application (DCA)|||Computer Applications' => [
            'Data Entry Operator',
            'Computer Operator',
            'Office Assistant',
            'Typist',
            'BPO Executive',
        ],
        'ITI Certificate|||Electrician' => [
            'Electrician',
            'Electrical Helper',
            'Wireman',
            'Electrical Maintenance Technician',
            'Panel Technician',
        ],
        'ITI Certificate|||Fitter' => [
            'Fitter',
            'Production Helper',
            'Machine Operator',
            'Maintenance Fitter',
            'Workshop Technician',
        ],
        'ITI Certificate|||Welder' => [
            'Welder',
            'Fabricator',
            'Pipe Welder',
            'Gas Cutter',
        ],
        'ITI Certificate|||Mechanic (Motor Vehicle)' => [
            'Auto Mechanic',
            'Vehicle Technician',
            'Service Advisor',
            'Two-Wheeler Mechanic',
            'Automobile Technician',
        ],
        'ITI Certificate|||Computer Operator & Programming Assistant (COPA)' => [
            'Computer Operator',
            'Data Entry Operator',
            'DTP Operator',
            'Office Assistant',
            'BPO Executive',
        ],
        'Science Stream|||PCM (Physics, Chemistry, Maths)' => [
            'Back Office Executive',
            'Data Entry Operator',
            'Customer Support Executive',
            'Sales Executive (Fresher)',
            'BPO Executive',
            'Field Executive',
        ],
        'Science Stream|||PCB (Physics, Chemistry, Biology)' => [
            'Lab Assistant',
            'Medical Representative',
            'Nursing Assistant',
            'Back Office Executive',
            'Customer Support Executive',
        ],
        'Commerce Stream|||With Mathematics' => [
            'Accounts Assistant',
            'Data Entry Operator',
            'Back Office Executive',
            'Billing Executive',
            'Customer Support Executive',
            'Banking Trainee',
        ],
        'Commerce Stream|||Without Mathematics' => [
            'Data Entry Operator',
            'Customer Support Executive',
            'Back Office Executive',
            'Sales Executive (Fresher)',
            'BPO Executive',
        ],
        'Secondary Education (Class X)|||General' => [
            'Helper',
            'Field Executive',
            'Delivery Executive',
            'Security Guard',
            'Office Boy / Peon',
            'Housekeeping Staff',
        ],
        'Primary Education|||General' => [
            'Helper',
            'Office Boy / Peon',
            'Housekeeping Staff',
            'Gardener',
            'Security Guard',
        ],
    ],

    'default_skill_suggestions' => [
        'Communication',
        'MS Office',
        'MS Excel',
        'Email Writing',
        'Data Entry',
        'Teamwork',
        'Time Management',
        'Problem Solving',
    ],
    'default_role_suggestions' => [
        'Executive',
        'Junior Executive',
        'Assistant',
        'Trainee',
        'Back Office Executive',
        'Customer Support Executive',
        'Sales Executive',
        'Operations Executive',
    ],

];
